steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "pull"
      - "docker.io/princetondalmet/princeton-flask-backend:latest" # Correct image reference

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "instances"
      - "update-container"
      - "princeton-flask-backend-instance"
      - "--container-image"
      - "docker.io/princetondalmet/princeton-flask-backend:latest" # Correct image reference
      - "--zone"
      - "northamerica-northeast2-a"

options:
  logging: CLOUD_LOGGING_ONLY
